apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init
  namespace: airflow
spec:
  template:
    spec:
      containers:
      - name: airflow-init
        image: apache/airflow:2.7.2
        command: [ "/bin/bash", "-c" ]
        args:
        - |
          airflow db init && \
          airflow users create \
            --username admin \
            --password admin \
            --firstname Gourav \
            --lastname Mishra \
            --role Admin \
            --email gourav@example.com
        envFrom:
        - configMapRef:
            name: airflow-config
      restartPolicy: OnFailure
